### ISSUE TITLE
Which framework should we use?

### ISSUE THREAD

**Issue by andreagrandi** [andreagrandi/covid-api#1]
We should pick a Python framework to be used for this API implementation:

- Django Rest Framework: https://www.django-rest-framework.org/
- FastAPI: https://fastapi.tiangolo.com

**Comment by audreyfeldroy** [comment]
What's your preference? I'm flexible!

**Comment by audreyfeldroy** [comment]
FastAPI looks really interesting...I have no experience with it but I like its promise of being fun and easy to learn 🙂

**Comment by andreagrandi** [comment]
> FastAPI looks really interesting...I have no experience with it but I like its promise of being fun and easy to learn 🙂

I've been using it for a couple of weeks only for an internal prototype. It doesn't come with "batteries included" (like Django). I also agree on the learning side!

**Comment by audreyfeldroy** [comment]
I was just talking with @rdegges here about FastAPI...apparently it's awesome, just not widely known. I'd love to try it out for this if you're up to it.

**Comment by MatMoore** [comment]
I've tried FastAPI for a personal project and I like it so far. I think it's quicker to get started with than Django Rest Framework, since DRF assumes you're already working with Django and then introduces more concepts on top of that.

**Comment by andreagrandi** [comment]
Let's continue with FastAPI then 👍
