### ISSUE TITLE
Make the root URL do something useful

### ISSUE THREAD

**Issue by MatMoore** [andreagrandi/covid-api#22]
Split from https://github.com/andreagrandi/covid-api/issues/20

Currently, the root URL (i.e. http://localhost:8000/) returns a 404 which is probably going to be confusing.

Can we redirect that to the docs, or put in an HTML landing page?

https://github.com/tiangolo/fastapi/issues/199 has an example of how to do redirects in FastAPI

For a landing page I think we can follow https://fastapi.tiangolo.com/tutorial/static-files/

Some ideas for things we could put on a landing page:
- A link to github, maybe like this https://github.blog/2008-12-19-github-ribbons/
- A link to the API documentation
- A simple example of what the API returns

**Comment by shiv-io** [comment]
Just created a pull request: https://github.com/andreagrandi/covid-api/pull/23

**Comment by andreagrandi** [comment]
> Just created a pull request: #23

Thanks for the PR!
