### ISSUE TITLE
Is the date of the file needed?

### ISSUE THREAD

**Issue by fundor333** [andreagrandi/covid-api#8]
This is the csv row into a BaseModel but we don't have the date of the file.

https://github.com/andreagrandi/covid-api/blob/45ecace14fc0a15791e901cef1bfeb58d65ea573/covidapi/db/schemas.py#L5-L15

Do we need it? Or we save only the last date of the data?

**Comment by andreagrandi** [comment]
No we don't need the file name nor the date contained in the file name. What's interesting is the `last_update` contained in the csv for each country.

When inserting / updating the data we will filter by country + province + last_update (it's important to have as much entries as possible, with different dates, for a single country, so we can build a timeline).
